version: '3.8'

services:
  fastapi:
    build: .
    container_name: pcbuilder-fastapi
    ports:
      - "8000:8000"
    env_file: ./backend-implementation/app/.env
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: pcbuilder-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pcbuilder 
    volumes:
     - postgres_data:/var/lib/postgresql/data
     
volumes:
  postgres_data: